import { ROUTE_ARGS_METADATA } from '@nestjs/common/constants';

export const TELEGRAM_MODULE_OPTIONS = 'TELEGRAM_MODULE_OPTIONS';
export const TELEGRAM_NAME = 'TELEGRAM_NAME';
export const DEFAULT_TELEGRAM_NAME = 'DEFAULT_TELEGRAM_NAME';

export const TELEGRAM_UPDATE_METADATA = 'TELEGRAM_UPDATE_METADATA';
export const TELEGRAM_SCENE_METADATA = 'TELEGRAM_SCENE_METADATA';
export const TELEGRAM_LISTENERS_METADATA = 'TELEGRAM_LISTENERS_METADATA';

export const TELEGRAM_SCENE_STEP_METADATA = 'TELEGRAM_SCENE_STEP_METADATA';
export const TELEGRAM_SCENE_ACTION_METADATA = 'TELEGRAM_SCENE_ACTION_METADATA';

export const PARAM_ARGS_METADATA = ROUTE_ARGS_METADATA;

export const TELEGRAM_SESSION_MANAGER = 'TelegramSessionManager';
export const TELEGRAM_SCENE_MANAGER = 'TelegramSceneManager';
export const TELEGRAM_HEAR_MANAGER = 'TelegramHearManager';
